# Generated by Django 2.1.7 on 2019-06-28 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricesRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 6, 28, 20, 32, 0, 468619), verbose_name='date')),
                ('type', models.TextField(default='', verbose_name='type')),
                ('category_id', models.IntegerField(default=0, verbose_name='category_id')),
                ('category_title', models.TextField(default='', verbose_name='category_title')),
                ('site_title', models.TextField(default='', verbose_name='site_title')),
                ('price_new', models.FloatField(default=-1.0, verbose_name='price_new')),
                ('price_old', models.FloatField(default=-1.0, verbose_name='price_old')),
                ('site_unit', models.TextField(default='', verbose_name='site_unit')),
                ('site_link', models.TextField(default='', verbose_name='site_link')),
                ('site_code', models.TextField(default='', verbose_name='site_code')),
                ('miss', models.IntegerField(default=0, verbose_name='miss')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
