# Generated by Django 2.1.7 on 2019-07-01 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_auto_20190701_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricesRaw2',
        ),
        migrations.AlterField(
            model_name='pricesraw',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 22, 33, 28, 48858), verbose_name='date'),
        ),
    ]
