# Generated by Django 2.1.7 on 2019-07-01 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_auto_20190701_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesraw',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 22, 35, 31, 225042), verbose_name='date'),
        ),
    ]
