# Generated by Django 2.1.7 on 2019-11-11 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_auto_20191107_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricesProcessed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('type', models.TextField(default='', verbose_name='type')),
                ('category_id', models.IntegerField(default=0, verbose_name='category_id')),
                ('category_title', models.TextField(default='', verbose_name='category_title')),
                ('site_title', models.TextField(default='', verbose_name='site_title')),
                ('price_new', models.FloatField(default=-1.0, verbose_name='price_new')),
                ('nsprice_f', models.FloatField(default=-1.0, verbose_name='price_new')),
                ('price_old', models.FloatField(default=-1.0, verbose_name='price_old')),
                ('site_unit', models.TextField(default='', verbose_name='site_unit')),
                ('site_link', models.TextField(default='', verbose_name='site_link')),
                ('site_code', models.TextField(default='', verbose_name='site_code')),
                ('miss', models.IntegerField(default=0, verbose_name='miss')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
